### ISSUE TITLE
bug: account.go subscription id may be `nil` causing panic and nil pointer deref

### ISSUE THREAD

**Issue by matt-FFFFFF** [Azure/terraform-provider-azapi#566]
https://github.com/Azure/terraform-provider-azapi/blob/fc2e875f65f4aacda5214420525797f5cd8351c3/internal/clients/account.go#L59

If the subscription id is not configured in the provider and it falls back to az cli, if the user is not logged in then the `loadDefaultsFromAzCmd()` func will assign a nil value to the subscription and tenant ids.

The referenced line above means therefore needs a nil check to avoid this:

```
Stack trace from the terraform-provider-azapi_v1.14.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x879e7a]

goroutine 68 [running]:
github.com/Azure/terraform-provider-azapi/internal/clients.(*ResourceManagerAccount).GetSubscriptionId(0xc0001d94b0)
        github.com/Azure/terraform-provider-azapi/internal/clients/account.go:59 +0x13a
github.com/Azure/terraform-provider-azapi/internal/services.(*ClientConfigDataSource).Read(0xc0001127c0, {0xea1e128, 0xc00183a0c0}, {{{{0xea22f60, 0xc00183ab70}, {0xcba320, 0xc00183aab0}}, {0xea24fd8, 0xc0004bcd40}}, {{{0x0, ...}, ...}, ...}}, ...)
        github.com/Azure/terraform-provider-azapi/internal/services/azapi_client_config_data_source.go:78 +0x35f
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadDataSource(0xc0003b0820, {0xea1e128, 0xc00183a0c0}, 0xc00183a1b0, 0xc00001d6c8)
        github.com/hashicorp/terraform-plugin-framework@v1.7.0/internal/fwserver/server_readdatasource.go:79 +0x433
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadDataSource(0xc0003b0820, {0xea1e128?, 0xc001827ef0?}, 0xc000c81ce0)
        github.com/hashicorp/terraform-plugin-framework@v1.7.0/internal/proto6server/server_readdatasource.go:55 +0x41c
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadDataSource(0xc0002a8fa0, {0xea1e128?, 0xc001827200?}, 0xc0000ccaa0)
        github.com/hashicorp/terraform-plugin-go@v0.22.1/tfprotov6/tf6server/server.go:686 +0x416
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadDataSource_Handler({0xdb1880?, 0xc0002a8fa0}, {0xea1e128, 0xc001827200}, 0xc00040db80, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.22.1/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:572 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001c1200, {0xea1e128, 0xc001827170}, {0xea23880, 0xc0004824e0}, 0xc0016b1680, 0xc0003b21b0, 0xf02db60, 0x0)
        google.golang.org/grpc@v1.62.1/server.go:1386 +0xe23
google.golang.org/grpc.(*Server).handleStream(0xc0001c1200, {0xea23880, 0xc0004824e0}, 0xc0016b1680)
        google.golang.org/grpc@v1.62.1/server.go:1797 +0x100c
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.62.1/server.go:1027 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 36
        google.golang.org/grpc@v1.62.1/server.go:1038 +0x135

Error: The terraform-provider-azapi_v1.14.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by ms-henglu** [comment]
Hi @matt-FFFFFF ,

Thank you for taking time to report this issue!

I've opened this PR to fix it: https://github.com/Azure/terraform-provider-azapi/pull/568
